server:
  port: 8083

mysql:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cranberry?characterEncoding=UTF-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.kundy.cranberry.mapper: debug
    com.kundy.cranberry.mapper.JbMethodLockMapper: warn

zk:
  servers: 127.0.0.1:2181
  connectionTimeout: 5000



